/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("movies").del();
  await knex("movies").insert([
    {
      id: 1,
      title: "The Dark Knight",
      genre: "Action",
      happy_ending: "false",
      minutes: "152",
      poster_path: "http://localhost:5050/images/the-dark-knight.jpg",
    },
    {
      id: 2,
      title: "The Shawshank Redemption",
      genre: "Drama",
      happy_ending: "true",
      minutes: "142",
      poster_path: "http://localhost:5050/images/the-shawshank-redemption.jpg",
    },
    {
      id: 3,
      title: "Forrest Gump",
      genre: "Drama",
      happy_ending: "true",
      minutes: "142",
      poster_path: "http://localhost:5050/images/forrest-gump.jpg",
    },
    {
      id: 4,
      title: "Inception",
      genre: "Drama",
      happy_ending: "true",
      minutes: "148",
      poster_path: "http://localhost:5050/images/inception.jpg",
    },
    {
      id: 5,
      title: "The Godfather",
      genre: "Drama",
      happy_ending: "false",
      minutes: "175",
      poster_path: "http://localhost:5050/images/the-godfather.jpg",
    },
    {
      id: 6,
      title: "The Matrix",
      genre: "Action",
      happy_ending: "true",
      minutes: "136",
      poster_path: "http://localhost:5050/images/the-matrix.jpg",
    },
    {
      id: 7,
      title: "Toy Story",
      genre: "Animation",
      happy_ending: "true",
      minutes: "81",
      poster_path: "http://localhost:5050/images/toy-story.jpg",
    },
    {
      id: 8,
      title: "The Lord of the Rings: The Return of the King",
      genre: "Action",
      happy_ending: "true",
      minutes: "201",
      poster_path: "http://localhost:5050/images/lotr-return-of-the-king.jpg",
    },
    {
      id: 9,
      title: "Pulp Fiction",
      genre: "Drama",
      happy_ending: "false",
      minutes: "154",
      poster_path: "http://localhost:5050/images/pulp-fiction.jpg",
    },
    {
      id: 10,
      title: "Titanic",
      genre: "Drama",
      happy_ending: "false",
      minutes: "195",
      poster_path: "http://localhost:5050/images/titanic.jpg",
    },
    {
      id: 11,
      title: "The Lion King",
      genre: "Animation",
      happy_ending: "false",
      minutes: "88",
      poster_path: "http://localhost:5050/images/the-lion-king.jpg",
    },
    {
      id: 12,
      title: "Gladiator",
      genre: "Action",
      happy_ending: "false",
      minutes: "155",
      poster_path: "http://localhost:5050/images/gladiator.jpg",
    },
    {
      id: 13,
      title: "The Departed",
      genre: "Drama",
      happy_ending: "false",
      minutes: "151",
      poster_path: "http://localhost:5050/images/the-departed.jpg",
    },
    {
      id: 14,
      title: "Saving Private Ryan",
      genre: "Drama",
      happy_ending: "true",
      minutes: "169",
      poster_path: "http://localhost:5050/images/saving-private-ryan.jpg",
    },
    {
      id: 15,
      title: "The Avengers",
      genre: "Action",
      happy_ending: "true",
      minutes: "143",
      poster_path: "http://localhost:5050/images/the-avengers.jpg",
    },
    {
      id: 16,
      title: "Jurassic Park",
      genre: "Action",
      happy_ending: "true",
      minutes: "127",
      poster_path: "http://localhost:5050/images/jurassic-park.jpg",
    },
    {
      id: 17,
      title: "The Silence of the Lambs",
      genre: "Thriller",
      happy_ending: "false",
      minutes: "118",
      poster_path: "http://localhost:5050/images/silence-of-the-lambs.jpg",
    },
    {
      id: 18,
      title: "The Wizard of Oz",
      genre: "Adventure",
      happy_ending: "true",
      minutes: "102",
      poster_path: "http://localhost:5050/images/wizard-of-oz.jpg",
    },
    {
      id: 19,
      title: "The Green Mile",
      genre: "Drama",
      happy_ending: "false",
      minutes: "189",
      poster_path: "http://localhost:5050/images/the-green-mile.jpg",
    },
    {
      id: 20,
      title: "The Sixth Sense",
      genre: "Drama",
      happy_ending: "false",
      minutes: "107",
      poster_path: "http://localhost:5050/images/the-sixth-sense.jpg",
    },
    {
      id: 21,
      title: "Interstellar",
      genre: "Drama",
      happy_ending: "true",
      minutes: "169",
      poster_path: "http://localhost:5050/images/interstellar.jpg",
    },
    {
      id: 22,
      title: "The Social Network",
      genre: "Drama",
      happy_ending: "false",
      minutes: "120",
      poster_path: "http://localhost:5050/images/the-social-network.jpg",
    },
    {
      id: 23,
      title: "The Sound of Music",
      genre: "Drama",
      happy_ending: "true",
      minutes: "174",
      poster_path: "http://localhost:5050/images/the-sound-of-music.jpg",
    },

    {
      id: 25,
      title: "The Matrix Reloaded",
      genre: "Action",
      happy_ending: "true",
      minutes: "138",
      poster_path: "http://localhost:5050/images/the-matrix-reloaded.jpg",
    },
    {
      id: 26,
      title: "The Terminator",
      genre: "Action",
      happy_ending: "false",
      minutes: "107",
      poster_path: "http://localhost:5050/images/the-terminator.jpg",
    },
    {
      id: 27,
      title: "The Exorcist",
      genre: "Thriller",
      happy_ending: "false",
      minutes: "122",
      poster_path: "http://localhost:5050/images/the-exorcist.jpg",
    },
    {
      id: 28,
      title: "Shrek",
      genre: "Animation",
      happy_ending: "true",
      minutes: "90",
      poster_path: "http://localhost:5050/images/shrek.jpg",
    },
    {
      id: 29,
      title: "The Godfather: Part II",
      genre: "Drama",
      happy_ending: "false",
      minutes: "202",
      poster_path: "http://localhost:5050/images/the-godfather-part-II.jpg",
    },
    {
      id: 30,
      title: "The Martian",
      genre: "Action",
      happy_ending: "true",
      minutes: "144",
      poster_path: "http://localhost:5050/images/the-martian.jpg",
    },
    {
      id: 31,
      title: "Finding Nemo",
      genre: "Animation",
      happy_ending: "true",
      minutes: "100",
      poster_path: "http://localhost:5050/images/finding-nemo.jpg",
    },
    {
      id: 32,
      title: "Raiders of the Lost Ark",
      genre: "Action",
      happy_ending: "true",
      minutes: "115",
      poster_path: "http://localhost:5050/images/raiders-of-the-lost-ark.jpg",
    },
    {
      id: 33,
      title: "Django Unchained",
      genre: "Drama",
      happy_ending: "false",
      minutes: "165",
      poster_path: "http://localhost:5050/images/django-unchained.jpg",
    },
    {
      id: 34,
      title: "The Lion King (2019)",
      genre: "Animation",
      happy_ending: "false",
      minutes: "118",
      poster_path: "http://localhost:5050/images/lion-king-2019.jpg",
    },
    {
      id: 35,
      title: "Schindler's List",
      genre: "Drama",
      happy_ending: "true",
      minutes: "195",
      poster_path: "http://localhost:5050/images/schindlers-list.jpg",
    },
    {
      id: 36,
      title: "The Incredibles",
      genre: "Animation",
      happy_ending: "true",
      minutes: "115",
      poster_path: "http://localhost:5050/images/the-incredibles.jpg",
    },
    {
      id: 37,
      title: "Back to the Future",
      genre: "Action",
      happy_ending: "true",
      minutes: "116",
      poster_path: "http://localhost:5050/images/back-to-the-future.jpg",
    },
    {
      id: 38,
      title: "Goodfellas",
      genre: "Drama",
      happy_ending: "false",
      minutes: "146",
      poster_path: "http://localhost:5050/images/goodfellas.jpg",
    },
    {
      id: 39,
      title: "A Clockwork Orange",
      genre: "Drama",
      happy_ending: "true",
      minutes: "136",
      poster_path: "http://localhost:5050/images/a-clockwork-orange.jpg",
    },
    {
      id: 40,
      title: "Avatar",
      genre: "Action",
      happy_ending: "true",
      minutes: "162",
      poster_path: "http://localhost:5050/images/avatar.jpg",
    },
    {
      id: 41,
      title: "The Prestige",
      genre: "Thriller",
      happy_ending: "true",
      minutes: "130",
      poster_path: "http://localhost:5050/images/the-prestige.jpg",
    },
    {
      id: 42,
      title: "Black Panther",
      genre: "Action",
      happy_ending: "true",
      minutes: "134",
      poster_path: "http://localhost:5050/images/black-panther.jpg",
    },
    {
      id: 43,
      title: "The Godfather: Part III",
      genre: "Drama",
      happy_ending: "false",
      minutes: "162",
      poster_path: "http://localhost:5050/images/godfather-part-III.jpg",
    },
    {
      id: 45,
      title: "Memento",
      genre: "Thriller",
      happy_ending: "true",
      minutes: "113",
      poster_path: "http://localhost:5050/images/memento.jpg",
    },
    {
      id: 46,
      title: "Spirited Away",
      genre: "Animation",
      happy_ending: "true",
      minutes: "125",
      poster_path: "http://localhost:5050/images/spirited-away.jpg",
    },
    {
      id: 48,
      title: "The Revenant",
      genre: "Drama",
      happy_ending: "false",
      minutes: "156",
      poster_path: "http://localhost:5050/images/the-revenant.jpg",
    },
    {
      id: 49,
      title: "The Breakfast Club",
      genre: "Drama",
      happy_ending: "true",
      minutes: "97",
      poster_path: "http://localhost:5050/images/the-breakfast-club.jpg",
    },
    {
      id: 50,
      title: "The Shining",
      genre: "Thriller",
      happy_ending: "false",
      minutes: "146",
      poster_path: "http://localhost:5050/images/the-shining.jpg",
    },
    {
      id: 51,
      title: "The Dark Knight Rises",
      genre: "Drama",
      happy_ending: "true",
      minutes: "164",
      poster_path: "http://localhost:5050/images/the-dark-knight-rises.jpg",
    },
    {
      id: 52,
      title: "The Truman Show",
      genre: "Drama",
      happy_ending: "true",
      minutes: "103",
      poster_path: "http://localhost:5050/images/the-truman-show.jpg",
    },
    {
      id: 53,
      title: "The Good, the Bad and the Ugly",
      genre: "Action",
      happy_ending: "true",
      minutes: "178",
      poster_path:
        "http://localhost:5050/images/the-good-the-bad-and-the-ugly.jpg",
    },
    {
      id: 54,
      title: "Jaws",
      genre: "Thriller",
      happy_ending: "false",
      minutes: "124",
      poster_path: "http://localhost:5050/images/jaws.jpg",
    },
    {
      id: 55,
      title: "Kill Bill: Vol. 1",
      genre: "Action",
      happy_ending: "false",
      minutes: "111",
      poster_path: "http://localhost:5050/images/kill-bill-vol-1.jpg",
    },

    {
      id: 57,
      title: "Indiana Jones and the Last Crusade",
      genre: "Action",
      happy_ending: "true",
      minutes: "127",
      poster_path:
        "http://localhost:5050/images/indiana-jones-and-the-last-crusade.jpg",
    },
    {
      id: 58,
      title: "The Princess Bride",
      genre: "Action",
      happy_ending: "true",
      minutes: "98",
      poster_path: "http://localhost:5050/images/the-princess-bride.jpg",
    },

    {
      id: 63,
      title: "Alien",
      genre: "Action",
      happy_ending: "false",
      minutes: "117",
      poster_path: "http://localhost:5050/images/alien.jpg",
    },
    {
      id: 76,
      title: "The King's Speech",
      genre: "Drama",
      happy_ending: "true",
      minutes: "118",
      poster_path: "http://localhost:5050/images/the-kings-speech.jpg",
    },
    {
      id: 77,
      title: "Amélie",
      genre: "Action",
      happy_ending: "true",
      minutes: "122",
      poster_path: "http://localhost:5050/images/amelie.jpg",
    },
    {
      id: 80,
      title: "Life is Beautiful",
      genre: "Drama",
      happy_ending: "true",
      minutes: "116",
      poster_path: "http://localhost:5050/images/life-is-beautiful.jpg",
    },
    {
      id: 81,
      title: "The Grand Budapest Hotel",
      genre: "Drama",
      happy_ending: "true",
      minutes: "99",
      poster_path: "http://localhost:5050/images/the-grand-budapest-hotel.jpg",
    },

    {
      id: 83,
      title: "The Lord of the Rings: The Fellowship of the Ring",
      genre: "Action",
      happy_ending: "true",
      minutes: "178",
      poster_path:
        "http://localhost:5050/images/lotr-the-fellowship-of-the-ring.jpg",
    },
    {
      id: 84,
      title: "Braveheart",
      genre: "Drama",
      happy_ending: "false",
      minutes: "178",
      poster_path: "http://localhost:5050/images/braveheart.jpg",
    },
    {
      id: 87,
      title: "Good Will Hunting",
      genre: "Drama",
      happy_ending: "true",
      minutes: "126",
      poster_path: "http://localhost:5050/images/good-will-hunting.jpg",
    },
    {
      id: 91,
      title: "Soul",
      genre: "Animation",
      happy_ending: "true",
      minutes: "100",
      poster_path: "http://localhost:5050/images/soul.jpg",
    },
    {
      id: 93,
      title: "The Pursuit of Happyness",
      genre: "Drama",
      happy_ending: "true",
      minutes: "117",
      poster_path: "http://localhost:5050/images/the-pursuit-of-happiness.jpg",
    },

    {
      id: 95,
      title: "WALL·E",
      genre: "Animation",
      happy_ending: "true",
      minutes: "98",
      poster_path: "http://localhost:5050/images/wall-e.jpg",
    },
    {
      id: 97,
      title: "Ratatouille",
      genre: "Animation",
      happy_ending: "true",
      minutes: "111",
      poster_path: "http://localhost:5050/images/ratatouille.jpg",
    },
    {
      id: 98,
      title: "Up",
      genre: "Animation",
      happy_ending: "false",
      minutes: "96",
      poster_path: "http://localhost:5050/images/up.jpg",
    },
    {
      id: 99,
      title: "Toy Story 3",
      genre: "Animation",
      happy_ending: "false",
      minutes: "103",
      poster_path: "http://localhost:5050/images/toy-story-3.jpg",
    },
    {
      id: 100,
      title: "Inside Out",
      genre: "Animation",
      happy_ending: "false",
      minutes: "95",
      poster_path: "http://localhost:5050/images/inside-out.jpg",
    },
    {
      id: 101,
      title: "Coco",
      genre: "Animation",
      happy_ending: "false",
      minutes: "105",
      poster_path: "http://localhost:5050/images/coco.jpg",
    },
    {
      id: 102,
      title: "Monsters, Inc.",
      genre: "Animation",
      happy_ending: "false",
      minutes: "92",
      poster_path: "http://localhost:5050/images/monsters-inc.jpg",
    },
    {
      id: 103,
      title: "Finding Dory",
      genre: "Animation",
      happy_ending: "true",
      minutes: "97",
      poster_path: "http://localhost:5050/images/finding-dory.jpg",
    },
    {
      id: 104,
      title: "Zootopia",
      genre: "Animation",
      happy_ending: "true",
      minutes: "108",
      poster_path: "http://localhost:5050/images/zootopia.jpg",
    },

    {
      id: 106,
      title: "Moana",
      genre: "Animation",
      happy_ending: "true",
      minutes: "107",
      poster_path: "http://localhost:5050/images/moana.jpg",
    },
    {
      id: 107,
      title: "The Croods",
      genre: "Animation",
      happy_ending: "true",
      minutes: "98",
      poster_path: "http://localhost:5050/images/the-croods.jpg",
    },
    {
      id: 108,
      title: "Sing",
      genre: "Animation",
      happy_ending: "true",
      minutes: "108",
      poster_path: "http://localhost:5050/images/sing.jpg",
    },
    {
      id: 109,
      title: "Trolls",
      genre: "Animation",
      happy_ending: "true",
      minutes: "92",
      poster_path: "http://localhost:5050/images/trolls.jpg",
    },
    {
      id: 110,
      title: "The Boss Baby",
      genre: "Animation",
      happy_ending: "true",
      minutes: "97",
      poster_path: "http://localhost:5050/images/the-boss-baby.jpg",
    },
    {
      id: 112,
      title: "The Secret Life of Pets",
      genre: "Animation",
      happy_ending: "true",
      minutes: "87",
      poster_path: "http://localhost:5050/images/secret-life-of-pets.jpg",
    },
    {
      id: 113,
      title: "Despicable Me",
      genre: "Animation",
      happy_ending: "true",
      minutes: "95",
      poster_path: "http://localhost:5050/images/despicable-me.jpg",
    },
    {
      id: 114,
      title: "Madagascar",
      genre: "Animation",
      happy_ending: "true",
      minutes: "86",
      poster_path: "http://localhost:5050/images/madagascar.jpg",
    },
    {
      id: 115,
      title: "How to Train Your Dragon",
      genre: "Animation",
      happy_ending: "true",
      minutes: "98",
      poster_path: "http://localhost:5050/images/how-to-train-a-dragon.jpg",
    },
    {
      id: 116,
      title: "The Angry Birds Movie",
      genre: "Animation",
      happy_ending: "true",
      minutes: "97",
      poster_path: "http://localhost:5050/images/angry-birds-movie.jpg",
    },
    {
      id: 117,
      title: "Cars",
      genre: "Animation",
      happy_ending: "true",
      minutes: "117",
      poster_path: "http://localhost:5050/images/cars.jpg",
    },
    {
      id: 118,
      title: "Hotel Transylvania",
      genre: "Animation",
      happy_ending: "true",
      minutes: "91",
      poster_path: "http://localhost:5050/images/hotel-transylvania.jpg",
    },
    {
      id: 119,
      title: "Shrek 2",
      genre: "Animation",
      happy_ending: "true",
      minutes: "93",
      poster_path: "http://localhost:5050/images/shrek-2.jpg",
    },
    {
      id: 120,
      title: "Ice Age",
      genre: "Animation",
      happy_ending: "true",
      minutes: "81",
      poster_path: "http://localhost:5050/images/ice-age.jpg",
    },
    {
      id: 121,
      title: "Wreck-It Ralph",
      genre: "Animation",
      happy_ending: "true",
      minutes: "101",
      poster_path: "http://localhost:5050/images/wreck-it-ralph.jpg",
    },
    {
      id: 122,
      title: "The Lego Movie",
      genre: "Animation",
      happy_ending: "true",
      minutes: "100",
      poster_path: "http://localhost:5050/images/the-lego-movie.jpg",
    },
    {
      id: 125,
      title: "Kung Fu Panda",
      genre: "Animation",
      happy_ending: "true",
      minutes: "92",
      poster_path: "http://localhost:5050/images/kung-fu-panda.jpg",
    },
    {
      id: 134,
      title: "Big Hero 6",
      genre: "Animation",
      happy_ending: "true",
      minutes: "102",
      poster_path: "http://localhost:5050/images/big-hero-6.jpg",
    },
    {
      id: 150,
      title: "Frozen",
      genre: "Animation",
      happy_ending: "true",
      minutes: "102",
      poster_path: "http://localhost:5050/images/frozen.jpg",
    },
    {
      id: 151,
      title: "I am Legend",
      genre: "Action",
      happy_ending: "false",
      minutes: "101",
      poster_path: "http://localhost:5050/images/i-am-legend.jpg",
    },
    {
      id: 152,
      title: "Rambo: First Blood",
      genre: "Action",
      happy_ending: "false",
      minutes: "93",
      poster_path: "http://localhost:5050/images/rambo.jpg",
    },
    {
      id: 153,
      title: "Bambi",
      genre: "Animation",
      happy_ending: "false",
      minutes: "70",
      poster_path: "http://localhost:5050/images/bambi.jpg",
    },
    {
      id: 154,
      title: "Seven",
      genre: "Drama",
      happy_ending: "false",
      minutes: "127",
      poster_path: "http://localhost:5050/images/seven.jpg",
    },
    {
      id: 155,
      title: "The Judge",
      genre: "Drama",
      happy_ending: "false",
      minutes: "141",
      poster_path: "http://localhost:5050/images/the-judge.jpg",
    },
    {
      id: 156,
      title: "The Bucket List",
      genre: "Drama",
      happy_ending: "false",
      minutes: "97",
      poster_path: "http://localhost:5050/images/the-bucket-list.jpg",
    },
    {
      id: 157,
      title: "The Imitation Game",
      genre: "Drama",
      happy_ending: "false",
      minutes: "114",
      poster_path: "http://localhost:5050/images/the-imitation-game.jpg",
    },
    {
      id: 158,
      title: "The Book of Eli",
      genre: "Drama",
      happy_ending: "false",
      minutes: "118",
      poster_path: "http://localhost:5050/images/the-book-of-eli.jpg",
    },
    {
      id: 159,
      title: "Phone Booth",
      genre: "Thriller",
      happy_ending: "true",
      minutes: "81",
      poster_path: "http://localhost:5050/images/phone-booth.jpg",
    },
    {
      id: 160,
      title: "Girl with the Dragon Tattoo",
      genre: "Thriller",
      happy_ending: "true",
      minutes: "158",
      poster_path: "http://localhost:5050/images/girl-with-dragon-tattoo.jpg",
    },
    {
      id: 161,
      title: "Heat",
      genre: "Thriller",
      happy_ending: "true",
      minutes: "170",
      poster_path: "http://localhost:5050/images/heat.jpg",
    },
  ]);
};
